Sage-Bionetworks/stopadforms

- DESCRIPTION
- R/utils.R
- app.R
Changes include:
- Use reticulate branch of dccvalidator to avoid conflict with PythonEmbedInR. This is a temporary fix until dccvalidator@master uses reticulate.
- Add `tryCatch` in `get_display_name()` for getting `userName` or `displayName`. It was crashing the program if one did not exist. The error handling is to literally ignore it and do nothing, which is a terrible way to handle errors. Ultimately, this should be updated to a better way of handling the problem overall or just a better way to handle the errors.
- Add app.R for easy local deployment.
> A few changes for stability and ease

- R/mod-review-section.R
Don't show rows for which the response is NA. Currently, the section will show rows for variables that other submissions have input for, but the current submission does not have input for it.
> Filter out NA responses

- R/app-server.R
- R/mod-panel-section.R
- man/mod_panel_section.Rd
Fixes #8.
Adds ability to submit internal and external comments, as well as an overall score, on full submission. This is a feature of the panel tab. The submission comments and score are saved to a submission-scores Synapse table.
> Add internal/external comments

- DESCRIPTION
- renv.lock
The reticulate branch has been merged, so we can use the master branch now, and depend on version >=0.0.0.9009
> Use updated master dccvalidator branch

- R/mod-review-section.R
- renv.lock
Update the lockfile with the latest synapseforms. The latest version of synapseforms changes the column "submission" to "form_data_id" and `get_submission_names()` to `get_submission_ids()`. Make updates to use the correct names/functions. This will make creating user friendly submission names easier.
> Update synapseforms version and needed changes

- R/mod-panel-section.R
- R/mod-review-section.R
Updated the submission and section scoring tables to hold the formDataId (snake-case to be consistent with the rest of Synapse). Changed stopadforms to store this value and to lookup the submission by it. Since formDataId is unique, this reduces errors that could result in duplicate submission names (although we still need to not have duplicate submission names...).
Since the latest version of synapseforms removes the submission column and uses form_data_id, this changes the submission name uploaded to the Synapse table. If a person has commented on the same submission/section before the update and then tried to comment again after the update, the query would not get the previous comment. Instead, a second comment on a "different" submission would be added. This update makes stopadforms …
> Fix issues with new synapseforms version and updated tables

- R/mod-panel-section.R
- R/mod-review-section.R
Stacey asked that we not paginate the tables that show sections of people's responses, as it's easy to overlook some data if it's paginated.
> Don't paginate tables showing sections

- R/mod-review-section.R
Fixes #40.
The only change currently is to display "None, Poor, Fair, Good, Excellent" on the section scoring and for these to have specific values as defined in #40. The value that is saved to the section-scoring table in Synapse is the defined numeric value (ie 0, 0.1, 0.25,...).
Since the table structures did not change, the panel section shows the numeric values, not ordinal values, for the user scores. This works well for averaging the values and keeping the table simple, but also looks a little odd since a user would have scored something as "Poor", not 0.1. That said, these are values the clients chose themselves. Ultimately, I'm not sure which is better: let the panel table show the numeric values or change the panel table to show both the ordinal and numeric values.
> Ordinal section scoring

- R/app-server.R
- R/mod-panel-section.R
- R/mod-review-section.R
Fixes #50. The "Learn more" link takes you to here: https://docs.synapse.org/articles/accounts_certified_users_and_profile_validation.html
> Improve error message if user is not certified

- R/mod-review-section.R
- R/mod-view-all-section.R
Fixes #53. Not sure if it's better to replace this in the full dataset when it's loaded, or only in the subset of interest. My thinking was that in a given session, the user might not view the "basic data" section at all, so we don't want to do a lot of data wrangling operations that won't matter, but I'm open to other options. Thoughts @Aryllen?
> Replace therapeutic approach "both" with "prophylactic, symptomatic"

- DESCRIPTION
- R/app-ui.R
- R/mod-main.R
- R/mod-panel-section.R
This fixes refresh error.
From @brucehoff 
"I think what’s going on here is that when I reload the page I make the Shiny app’ think it’s getting a redirect back from Synapse and it tries to get an access token with the old auth’ code.  The app’ gets a 400 response from Synapse and displays the error message.
[11:48](https://sagebionetworks.slack.com/archives/C03N8UHRACQ/p1656614923834989)
The way to test the theory is to change the app’ so that the auth’ code is not available in the URL bar for ‘replay’."
https://github.com/curso-r/auth0/issues/54#issuecomment-719111543
https://sagebionetworks.jira.com/browse/SWC-5297
> fix refresh error

- .github/workflows/R-CMD-check.yaml
- .github/workflows/shinyapps_deploy.yml
See this ticket:
https://sagebionetworks.jira.com/browse/ALZ-151?atlOrigin=eyJpIjoiNmU3OGM1MmI4ZWQ1NDI4Y2FkMzA0NzI5YTUzMzk5MjUiLCJwIjoiaiJ9
Try to containerize the app so that we control the R version it relies on
If this works, we can pin the R version to the latest compatible version (4.2.3)
We can ensure that the test matrix is always testing that version (4.2.3)
> attempt to pin R container

- .github/workflows/shinyapps_deploy.yml
See failure from latest deployment
https://github.com/Sage-Bionetworks/stopadforms/actions/runs/5084191712
Possible Bug fix:
https://stackoverflow.com/questions/42828083/error-while-loading-shared-libraries-usr-local-lib64-libssl-so-1-1
Let me know about additional ideas (nothing urgent)
> add linux depedency openssl11-libs

- .github/workflows/pkgdown.yaml
Hi all,
The staging instance for this app seems to work:
https://sagebio.shinyapps.io/stopadforms-staging/
Please try it out!
pkgdown.yaml is outdated and failing; I made updates for it to run on Ubuntu-20.04 and rocker/rstudio:4.1.3 container
From @andrewelamb , deployments to shinyapps.io can be a bit of trial and error, so we'll encounter a bit of this.
> fixes for pkgdown

- .github/workflows/shinyapps_deploy.yml
Update `rsconnect` command to handle missing deployment records.
Deployment error:
Error in `shouldUpdateApp()`:
! Discovered a previously deployed app named "stopadforms-staging"
(View it at <https://***.shinyapps.io/stopadforms-staging/>)
ℹ Set `forceUpdate = TRUE` to update it.
ℹ Supply a unique `appName` to deploy a new application.
From the [rsconnect docs:](https://cran.r-project.org/web/packages/rsconnect/rsconnect.pdf)
forceUpdate What should happen if there’s no deployment record for the app, but there’s an app with the same name on the server? If TRUE, will always update the previously-deployed app. If FALSE, will ask the user what to do, or fail if not in an interactive context.
> Add forceUpdate parameter to rsconnect::deployApp

- renv.lock
Future versions of reticulate are too smart when handling Python classes that extend from primitive Python types.
Use a less smart version of reticulate
> ALZ-136: Lock down reticulate version

- R/mod-panel-section.R
This uses a reacttable option to ensure all rows are expanded by default
> [ALZ-182] Expand all rows by default in summary

- R/mod-panel-section.R
This makes sure that sections appear in the same order as the review tab.
> [ALZ-94] Reorder sections in summarize tab

- R/mod-panel-section.R
@JessterB @thomasyu888 turns out there were more fixes needed for internal and external comment surfacing.... the field was named "comments" but in the DB its "comment" 😄 so i standardized that.
> FIX: surface internal and external comments

- R/mod-view-all-section.R
This PR adds expand and collapse all buttons on the view all submissions tab
> [ALZ-109] Expand and collapse all submissions

- R/data-gather-clean.R
This PR will include [1] as a suffix for the step, even when there's only a single experiment for that step.
> [ALZ-245] Append step number always, even when one exp
