Sage-Bionetworks/stopadforms

.Rbuildignore, .Rprofile, DESCRIPTION, R/app-ui.R, R/mod-panel-section.R, R/mod-review-section.R, man/mod_panel_section.Rd, man/mod_review_section.Rd, renv.lock, renv/.gitignore, renv/activate.R, renv/settings.dcf
Add functionality for getting and displaying the real data. Adds package management with renv.
=> Add real data

R/mod-review-section.R
=> Fix section bug by checking if metadata index exists

tests/testthat/test-data-gather-clean.R
Adds some tests for `create_table_by_sections()`
=> Add some tests

DESCRIPTION, R/mod-panel-section.R, R/mod-review-section.R
=> Reset scores and comments after submission

R/app-server.R
Fixes #44 
Not sure what is the best way to handle the case when the user isn't certified. It might be good to still let them view data, they just won't be able to submit reviews. So we could prevent clicking the submit button if they're not certified? @Aryllen what do you think?
=> Require user to be in team

man/mod_panel_section.Rd, man/mod_review_section.Rd
Forgot to generate these files in #51
=> Add user param to rendered documentation

DESCRIPTION, renv.lock
* Update to dev version of usethis so we can use `use_github_actions()`
* Add GitHub URL to DESCRIPTION because usethis wants it to be there
=> Prep for using github actions

R/mod-review-section.R, R/mod-view-all-section.R, R/reorder-steps.R, tests/testthat/test-mod-review-section.R
=> Reorder steps

.Rprofile, .github/workflows/R-CMD-check.yaml, DESCRIPTION, renv.lock
=> Try to fix GitHub actions

DESCRIPTION, R/data-gather-clean.R, man/create_table_from_json_file.Rd, man/map_sections_variables.Rd, renv.lock, tests/testthat/test-data-gather-clean.R
=> Show all sections and variables

.github/workflows/R-CMD-check.yaml, R/app-config.R, R/mod-panel-section.R, config.yml, inst/config.yml
This is a very minor code fix.  The purpose is to solve an issue where the submission data was not joining properly with the stored synapse data.  Ultimately, it's an extra whitespace problem.  Please verify and approve so that we can deploy this fix to shiny server pro.
=> ALZ57 fix whitespace bug

.github/workflows/R-CMD-check.yaml
Test new 
https://github.com/r-lib/actions#releases-and-tags
=> Development maintenance

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml
source activate with renv::lock()
=> change renv::lock() install

.github/workflows/shinyapps_deploy.yml
deploy on pull request approval and merge test
=> deploy test

.github/workflows/shinyapps_deploy.yml
Checking release on pull request and merge
=> Release 1.0.0

R/score.R
Introduced mild hack to preserve functionality of pivot_longer function that changed with tidyr update on January 24th, 2023 https://tidyr.tidyverse.org/news/index.html
=> ALZ-138 bug fix

.github/workflows/R-CMD-check.yaml, .github/workflows/shinyapps_deploy.yml
Update the OS version from 18.04
=> update OS versions

R/mod-synapse-oauth.R
Hopefully, this is temporary fix for the installation issue
=> Fix pandas dependency issue

.github/workflows/shinyapps_deploy.yml
failed previously, trying something different
https://stackoverflow.com/questions/64950324/unable-to-locate-package-openssl-dev
=> openssl libssl-dev added

.github/workflows/R-CMD-check.yaml, .github/workflows/shinyapps_deploy.yml, R/app-ui.R, R/mod-synapse-oauth.R, README.md, app.R, renv.lock, renv/.gitignore, renv/activate.R
* Upgrade renv dependencies
* Add workflow dispatch
* no longer need to support interactive mode, because people can create a oauth client that links to local host.
=> Application upgrade

.github/workflows/shinyapps_deploy.yml, install-pkgs.R
**Problem**
The shiny deployment is failing for some reason
**Solution**
Use renv to install all dependencies
=> [ALZ-149] Fix deployment of shiny apps

R/data-gather-clean.R, R/mod-main.R
This PR splits the possible error conditions with separate tryCatch blocks, attempting to give an informative error message in the case of different types of errors
=> [ALZ-159] TryCatch blocks for each possible error

R/mod-panel-section.R
Based on the submission id and the user, set the 3 fields in the review page plus the text of the submit button accordingly
=> [ALZ-167] Surface previous submission if available

R/mod-panel-section.R
This adds two buttons to expand and collapse submissions respectively.
=> [ALZ-108] Expand and Collapse submissions

R/data-gather-clean.R
This should address the comments in ALZ-173
=> [ALZ-173] Clean up the logging display

R/mod-panel-section.R
This PR splits the submissions tab to have a read only calculated overall score, and a reviewed overall score
=> [ALZ-110] Reviewed vs Calculated scores

R/data-gather-clean.R, R/mod-main.R, R/mod-review-section.R, R/mod-view-all-section.R, man/mod_view_all_section.Rd
This PR adds support for showing the submission date in dropdowns, and sorting across all modules based on that date.
=> [ALZ-106] [ALZ-166] Dates in dropdowns

R/mod-review-section.R
This PR will surface a user's previous submission and display it in the textbox, if available.
=> [ALZ-93] Surface previous submission if available

R/score.R
This PR will score a species NA selection as 0 in the weighting
=> [ALZ-210] Score as 0 when NA for species is selected

R/mod-panel-section.R
This should fix the bug with internal and external comment loading
=> [ALZ-167] Fix updating internal and ext comments

R/mod-synapse-oauth.R
This PR updates the code to create a venv which uses the new python client, which should fix the persistence issues with the data.
=> [ALZ-164] Use new synapse python client

R/app-ui.R, R/mod-panel-section.R
Here is my attempt at button alignment. Note the search bar has a different styling... because that comes directly from the table output below. So i kind of had to hack it to move it. We can probably improve the styling of that further if you want.
=> [ALZ-218] Button alignment in VSS

R/mod-review-section.R
This PR uses etags to ensure persistence of data across sessions
=> [ALZ-242] Finally fix persistence issues

R/mod-panel-section.R, R/score.R
This PR adds section rollup scores to the VSS tab.
=> [ALZ-105] Add section rollup scores to table

R/mod-panel-section.R
This PR does the same additions to the VSS tab as the review tab
=> [ALZ-238] Update persistence for VSS

R/score.R
This PR includes ld50 in the zeroing out when NA for species
=> [ALZ-210] Include ld50 in the zeroing

R/mod-panel-section.R, R/mod-view-all-section.R, R/reorder-steps.R
This PR fixes the ordering of sections in VSS across all submissions.
=> [ALZ-94] Fix VSS order of sections

R/data-gather-clean.R, R/mod-review-section.R, R/mod-view-all-section.R
This PR fixes the date display in the View All Submissions tab, and the button alignment issue
=> [ALZ-247] [ALZ-246] Fix VAS displays

R/mod-panel-section.R
This PR ensures that on submission of new data, the label is appropriately updated to Overwrite
=> [ALZ-248] Change label to overwrite on submit

R/mod-panel-section.R
This PR removes the rollup score column from VSS and instead puts the rollup score in the top level of each section in the score column.
=> Refactor rollup score to score column aggregation

R/mod-panel-section.R
This PR will surface the username in the overwrite button on VSS
=> [ALZ-176] Show username in overwrite on VSS

R/mod-panel-section.R, R/mod-review-section.R, R/mod-view-all-section.R
This should implement the desired visual tweaks on the VAS and VSS tabs.
=> [ALZ-251] Various visual tweaks

R/mod-panel-section.R
This PR adds a species column to the VSS table.
=> [ALZ-253] Add species column to VSS

R/mod-view-all-section.R
Missed this small tweak to VAS
=> [ALZ-251] Update Include Status label

R/data-gather-clean.R
This PR restricts the [1] suffix labeling to the 8 categories specified.
=> [ALZ-245] Restrict [1] to certain sections

R/mod-review-section.R
This PR makes the RS submission dropdown full width
=> [ALZ-256] Full width submissions dropdown

R/mod-panel-section.R
This PR ensures that the submissions table data (the form at the bottom of VSS) is refreshed when the Refresh Data button is selected.
=> [ALZ-249] Refresh data for submissions table as well

R/mod-view-all-section.R, data-raw/lookup_table.R
This PR cleans up the VAS tab labels
=> [ALZ-263] Clean VAS tab labels
